---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always
- import_tasks: mediaservices.yml
  when: "'mediaservices' in group_names"
  tags:
    - mediaservices

- import_tasks: nzb.yml
  when: "'nzbservices' in group_names"
  tags:
    - nzbservices

- import_tasks: plex.yml
  when: "'plexservers' in group_names"
  tags:
    - plexservices